### ISSUE TITLE
Verifying & Fixing OpenG2P issues

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#293]
We need to check whether the following issues are fixed in ACF. These are a set of issues Mark found during the sanity testing of the OpenG2P code merge.

https://github.com/orgs/OpenSPP/projects/6/views/1

You can add comments to each issue, whether the issue exists in ACF dev or not.

**Comment by adriancris** [comment]
[Odoo error displayed after logging in](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46454207) - cannot be replicated in ACF Dev

**Comment by adriancris** [comment]
[Cycle approver role issue](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46456778) - cannot be replicated in ACF Dev

**Comment by adriancris** [comment]
[No error message when attempting to approve cash entitlements from entitlement list view](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46457931) - @dasunhegoda @gonzalesedwin1123, bug can be replicated in ACF dev


https://github.com/OpenSPP/openspp-registry/assets/138551361/d3205023-fc21-43c9-b980-f5e47c6ff874

**Comment by adriancris** [comment]
[Unable to create a program as Program manager](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46458720) - @dasunhegoda @gonzalesedwin1123, bug can be replicated in ACF dev

PRECONDITION:
Must be logged in as Program Manager


https://github.com/OpenSPP/openspp-registry/assets/138551361/cc095279-e989-4c9d-b443-41a6b77b57b4

**Comment by adriancris** [comment]
[Import eligible registrant button missing](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=47958711) - cannot be replicated in ACF Dev

**Comment by adriancris** [comment]
[In-kind program issues](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=48043533) - cannot be replicated in ACF Dev

**Comment by adriancris** [comment]
[Action buttons distorted when zoom scale of local machine is more than 100%](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=48854126) - @dasunhegoda @gonzalesedwin1123, bug can be replicated in ACF dev 


https://github.com/OpenSPP/openspp-registry/assets/138551361/44d1fd30-634d-4c39-a92e-c062f094321c

**Comment by adriancris** [comment]
[Improve error message when user account is expired and unable to login](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=48965010) - @dasunhegoda @gonzalesedwin1123, bug can be replicated in ACF dev


https://github.com/OpenSPP/openspp-registry/assets/138551361/bc662c66-4ef2-494a-a859-a9a3675aee23

**Comment by adriancris** [comment]
[Duplicated fields in Custom Filter](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49381246) - @dasunhegoda @gonzalesedwin1123, bug can be replicated in ACF dev

![image](https://github.com/OpenSPP/openspp-registry/assets/138551361/d0a71ea2-7bae-4a82-9582-74e8e12da31c)
![image](https://github.com/OpenSPP/openspp-registry/assets/138551361/c0ae2941-1c5d-4948-a89a-9d828139fd79)

**Comment by dasunhegoda** [comment]
Thanks @adriancris!

Once the @emjay0921 is back, he can start working on the bugs that can be replicated.  

If the issue resides in the OpenG2P codebase, we can inform them.

cc: @gonzalesedwin1123

**Comment by adriancris** [comment]
@dasunhegoda @emjay0921 

[Overwrite match in import match feature not working as expected](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=51221310) - this can also be replicated in ACF dev.

**Comment by emjay0921** [comment]
Done: 

- [No error message when attempting to approve cash entitlements from entitlement list view](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46457931)
- [Unable to create a program as Program manager](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46458720)
- [Action buttons distorted when zoom scale of local machine is more than 100%](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=48854126)
- [Duplicated fields in Custom Filter](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49381246)

Working on:

[Overwrite match in import match feature not working as expected](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=51221310)

**Comment by emjay0921** [comment]
Pushed PR for [
Import eligible registrant button missing](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=47958711)

**Comment by emjay0921** [comment]
Continue working on [Overwrite match in import match feature not working as expected](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=51221310).

**Comment by emjay0921** [comment]
Working on this today: [Remove unnecessary columns on in-kind entitlement transactions](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49387978)

**Comment by adriancris** [comment]
Update:
@dasunhegoda, @emjay0921, @gonzalesedwin1123 

FIXED
- [No error message when attempting to approve cash entitlements from entitlement list view](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46457931)
- [Action buttons distorted when zoom scale of local machine is more than 100%](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=48854126)

BLOCKED
- [Unable to create a program as Program manager](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46458720)
Reason: User roles are not yet configured

- [Overwrite match in import match feature not working as expected](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=51221310)
Reason: No import matching yet

- [Remove unnecessary columns on in-kind entitlement transactions](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49387978)
Reason: The unnecessary columns on in-kind entitlements are also in the POST In-kind Entitlement API. Since the APIs are not yet configured, I cannot verify if the unnecessary input parameters (unnecessary columns on in-kind entitlements) are not there anymore. 

NOT YET FIXED
- [Duplicated fields in Custom Filter](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49381246) (Tags and Kind still have duplicates in ACF DEV)

OTHERS
- [Import eligible registrant button missing](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=47958711)
Reason: @emjay0921 remove the button from being hidden but openg2p has kept hidden it

**Comment by emjay0921** [comment]
[Unable to create a program as Program manager](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46458720) - This are Done with @reichie020212's Merged [PR](https://github.com/OpenSPP/openspp-modules/pull/426/files)

**Comment by emjay0921** [comment]
[Overwrite match in import match feature not working as expected](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=51221310) - Since the changes on JS on Odoo 17 this feature is not yet good and might need to create a separate ticket for this to investigate and fix thoroughly. cc @dasunhegoda

**Comment by emjay0921** [comment]
[Remove unnecessary columns on in-kind entitlement transactions](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49387978) - Here's the PR for this: https://github.com/OpenSPP/openspp-modules/pull/486

**Comment by emjay0921** [comment]
[Duplicated fields in Custom Filter](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49381246) - Here's the PR for this: https://github.com/OpenSPP/openspp-modules/pull/487

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
remaining issue to be moved on a separate ticket
[Overwrite match in import match feature not working as expected](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=51221310) - fail, michael suggests to create a separate ticket for it


[Unable to create a program as Program manager](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=46458720) - pass

[Remove unnecessary columns on in-kind entitlement transactions](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49387978) - pass , the headers are correct, for cash,it uses amount charged and value remaining
for in-kind it uses quantity remaining and quantity


[Duplicated fields in Custom Filter](https://github.com/orgs/OpenSPP/projects/6/views/1?pane=issue&itemId=49381246) - pass
![image](https://github.com/user-attachments/assets/cf45de65-3ffe-4855-adb5-65d404dd9410)
![image](https://github.com/user-attachments/assets/033f8cff-92c9-41eb-8fd6-ffa63300eaaa)
