### ISSUE TITLE
In-kind Entitlements cannot be approved all at once

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#420]
Video reference for reproducing issue:
https://drive.google.com/file/d/1G5Qw-RNNAdGj2bchpAoXp5n3XoGuJuUn/view?usp=drive_link

Document reference: 
Entitlements can be approved all at once in Entitlement page.
Approving Entitlements section.
https://docs.google.com/document/d/1dcUg3xcwo-8eGTnPjS5ddqTIG8WP1bmO/edit?pli=1

Existing in Instance:
ACF DEV
OpenG2P Sanity

EXPECTED BEHAVIOR: Approve option should be displayed when highlighting a few or all In-Kind Entitlements in Entitlements page.  The screenshot below is in cash.
![image (28)](https://github.com/OpenSPP/openspp-modules/assets/138551361/a1448096-e85e-4b69-afb3-19763b4e67df)

ACTUAL BEHAVIOR: No approve option.
![image](https://github.com/OpenSPP/openspp-modules/assets/138551361/e48fd4f6-9d4a-4069-973d-795ad620beda)

**Comment by jannahadlaon** [comment]
Testing is blocked.
I discovered that even after downloading these modules, I'm still unable to view the corresponding tabs (inventory and product configuration)
Tested in: https://qa-sp-mis.newlogic.net/
using sp-mis-qa credentials
![image](https://github.com/user-attachments/assets/9844de68-02c8-49d1-9b8a-739fb6abab1f)

**Comment by reichie020212** [comment]
@jannahadlaon The Inventory menu has been removed or hidden because of the module `OpenSPP Theme (Muk Theme)`. In order to show the Inventory menu, you need to do either of the following:

1. Uninstall the module `OpenSPP Theme (Muk Theme)`
2. Go to Settings -> Users & Companies -> Users -> select the account you're using -> Access Rights Tab -> Check the `Hide Menu` Role.

Will move this ticket back to QA.

**Comment by jannahadlaon** [comment]
Thank you @reichie020212!
I can verify that this is now working as expected. 
Tested in: https://qa-sp-mis.newlogic.net/
using sp-mis-qa credentials
![image](https://github.com/user-attachments/assets/c2040d81-edea-4217-b17b-9d22590a043a)
