### ISSUE TITLE
Overwrite match in import match feature not working as expected

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#421]
Replicated on : OpenSPP ](https://openg2p-sanity.newlogic-demo.com/web/login
Credentials Used: Admin account

Actual Result: when 'Overwrite match' is unchecked, it still overwrites the import data when there is a match found

Expected Result: when 'Overwrite match' is unchecked, importing data that matches existing data should not overwrite data and ignore changes.

![Image](https://github.com/OpenSPP/openspp-modules/assets/109514478/ae0e326a-2c45-4127-997e-63e4167641f1)

**Comment by emjay0921** [comment]
## NEW PR

https://github.com/OpenSPP/openspp-modules/pull/503

## REQUIREMENTS

Once deployed, install or upgrade the module `spp_import_match`.

## TO TEST
1. Navigate to Registry > Configuration > Import Match
2. Create or Upgrade an Import Match configuration for res_partner (Contact).
3. Add Field/s for the Import Match configuration.

- Test 1 (with overwrite match)
1. Check the overwrite match in the created Import Match configuration.
2. Navigate to Registry > Groups.
3. Click the Settings Icon ⚙️ > Import Records.
4. Upload Files (Make sure at least one record is matched with the configured fields in the Import Match).
5. Click Import
6. Check if the matched record was overwritten else fail.

- Test 2 (without overwrite match)
1. Uncheck the overwrite match in the created Import Match configuration.
2. Navigate to Registry > Groups.
3. Click the Settings Icon ⚙️ > Import Records.
4. Upload Files (Make sure at least one record is matched with the configured fields in the Import Match).
5. Click Import
6. Check if the matched record was not overwritten and skipped else fail.

cc @anthonymarkQA

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev
Related module: OpenSPP Import Match

Used given name as unique identifier and ticked overwrite match
![Image](https://github.com/user-attachments/assets/e0d09561-957f-42da-8038-3835ef1b9b4f)

Record duplicated instead of updating existing record
![Image](https://github.com/user-attachments/assets/8a460b15-9c66-4aa2-86a3-649750ac66f5)

**Comment by emjay0921** [comment]
@anthonymarkQA and I discussed this one before. Scenario where "Name" (Given or Family) is being used as the field identifier for import match doesn't work but other identifier fields works fine. 

I might need to have a clarification for this @kneckinator or @celinenilla, do we really need to make the "Name" as identifier? Because it is possible to have multiple matches with name. I just thought that import match was intended for unique fields as identifier.

**Comment by kneckinator** [comment]
@anthonymarkQA will raise tickets for the remaining issues and a "known" issue section will be added to the release notes along these lines:

Known issues:
- import matcher
  - the field "name" cannot be used as the key field when using the import matcher. If this is done, matching will not be done and instead new records will potentially be created.
  - if an import file has more than **two** duplicates, only the first two duplicates will be considered in the matching. Additional occurrences will be added as new records.

FYI @celinenilla

**Comment by anthonymarkQA** [comment]
Both known issues raised with a ticket separately

- https://github.com/OpenSPP/openspp-modules/issues/572
- https://github.com/OpenSPP/openspp-modules/issues/573
