### ISSUE TITLE
Improve error message when user account is expired and unable to login

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#423]
The error message needs to be improved for a user, when logging in with an expired user account in openspp test instance

for example, a simple error message in login screen: Your account has already expired , please contact admin for more information and support

Video link attached for reference:
https://drive.google.com/file/d/1iKisuLzcc1w9AOQlWIubFeNjZ_eFQeyI/view?usp=sharing

Investigation - Red
- This functionality is developed by OCA so I think the error can be improve by either OpenSPP or OpenG2P guys

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev
Tested in runboat instance http://openspp-openspp-modules-deploy-549-edb41b4feea3.runboatk8.newlogic-demo.com/web#cids=1&menu_id=224&action=336

Upon logging in with an expired user. i still am able to login and there is no access error message
![image](https://github.com/user-attachments/assets/b3b3a0c2-ee6f-4f5a-84d1-f5d847f9428f)

![image](https://github.com/user-attachments/assets/d3d7dc4f-8019-4ac1-9afe-14ac7ac9acbe)

**Comment by reichie020212** [comment]
@anthonymarkQA I removed the Test 2 because it seems that there is a change in the odoo's core module code regarding the Access Error that's why it is not showing anymore but rather it just disappear the menus that the user doesn't have permission to view.

for the `Upon logging in with an expired user. i still am able to login`, this is expected since what expired only is the role of the user not the actual user.

Returning this to QA

**Comment by anthonymarkQA** [comment]
Findings: Returned to DEV

for example. as system admin, if my account has an expired system admin role, upon login, the features i used to have access before becomes hidden. even though the reason is my access is just expired, this would confuse the user if there are issues with openspp. 

a message prompt upon login would be great that informs the user that the `system admin role has expired, contact support for more information. `and this message prompt behavior can have two options:

1. Modal appears only once.
2. Modal appears every login and a checkbox [ ]do not show this again , when ticked, will not display the message anymore

Note: if there are more than one roles expired. it will display in the modal at the same time.


To be reviewed with team @dasunhegoda

**Comment by reichie020212** [comment]
return this ticket to QA based on what was discussed in the standup. Thanks.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Setting this ticket to QA passed as agreed during standup. fixing the odoo error upon login alone is enough for now for this ticket.

![image](https://github.com/user-attachments/assets/1a63c0a5-4aca-46e0-b1c9-602b5bedf696)
