### ISSUE TITLE
Improve button text for import eligible registrant and Copy new beneficiaries from the program

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#640]
**Describe the bug**
As discused with BA,` Import eligible registrant` and `copy beneficiaries from the program` should be altered to `import new eligible registrants` and `copy new beneficiaries from the program` 
This is to align what the buttons actually do.

As a user i will assume "import eligible registrant" means if a `not eligible` group is already in the program, then i edit that group to be qualified for the program, when i press it, it will also change the already imported group's status from not eligible to enrolled . because the group was eligible already.

therefore import new eligible registrants is a better fit since it tells the user, it can only add new groups/individuals in the program that qualify for the program.

The same problem with `Copy beneficiaries from the program` button. it can only copy new beneficiaries from the program.

**To Reproduce**

1. Go to qa spmis and login as admin
2. In registry, go to configuration and create a tag "tag a1"
3. Assign this tag into two groups in registry
4. Create a program that targets groups with "tag a1" and auto import and enroll.
5. Inside your program, you should have 2 beneficiaries that have a status "enrolled"
6. Go to registry and remove the tag a1 from one of the groups then save.
7. Go back to program and click verify eligibility. This should change the unqualified group's state to not enrolled.
8. Go back to registry and add  "tag a1" back to the group then save
9. Go back to program then click import eligible registrant. as user, you would mistakenly expected it will also change that group's status in the beneficiaries tab from 'not eligible' to 'enrolled' since you made the group able to qualify again.
10

**Expected behavior**
Change button names to 

- `Import New Eligible Registrants` 
- `Copy New Beneficiaries from Program`

**Screenshots**
![image](https://github.com/user-attachments/assets/2889206f-84c2-434e-b049-ae51e55410d7)
![image](https://github.com/user-attachments/assets/57e9f9ef-778f-4f67-8435-99d4fb9be77d)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by celinenilla** [comment]
@gonzalesedwin1123 , can you please advise on the above?

**Comment by celinenilla** [comment]
@shashikala1998 , once @gonzalesedwin1123 is done reviewing it you can start working on it.

**Comment by gonzalesedwin1123** [comment]
@celinenilla I think @shashikala1998 can start working on this.

**Comment by anjclarise** [comment]
Verified this ticket and it is working as expected. 

Current behavior: 
Button text were improved to better understand it's use. Button text were changed resp to: **_Import new eligible registrants_** and **_Copy new beneficiaries from program_** _refer to screenshots below_

TEST STEPS:
1. Go to qa spmis and login as admin
2. In registry, go to configuration and create a tag "tag a1"
3. Assign this tag into two groups in registry
4. Create a program that targets groups with "tag a1" and auto import and enroll.
5. Inside your program, you should have 2 beneficiaries that have a status "enrolled"
6. Go to registry and remove the tag a1 from one of the groups then save.
7. Go back to program and click verify eligibility. This should change the unqualified group's state to not enrolled.
8. Go back to registry and add "tag a1" back to the group then save
9. Go back to program then click import eligible registrant. as user, you would mistakenly expected it will also change that group's status in the beneficiaries tab from 'not eligible' to 'enrolled' since you made the group able to qualify again.


Enrolled to a program with tags:
![image](https://github.com/user-attachments/assets/77a8df0b-61a1-4d8d-aaf1-3af88c68c0e2)

Program eligibility changed when tag was removed:
![image](https://github.com/user-attachments/assets/89ebdbc2-2d63-425e-8116-f3701005e319)

Copy new beneficiaries button:
![image](https://github.com/user-attachments/assets/14ecb4e6-483c-4252-92f4-c1474c857b87)

Import new eligible registrants button:
<img width="956" alt="image" src="https://github.com/user-attachments/assets/697d570f-056d-42d4-81ac-7af6a7784252">
