### ISSUE TITLE
Differentiate between eligible and compliant when using compliance module

### ISSUE THREAD

**Issue by celinenilla** [openspp-project/openspp-registry#649]
When using the compliance module it should be possible to see what beneficiaries are eligible but not compliant. Currently, after executing the compliance criteria, only the eligible AND compliant beneficiaries will display as eligible. It should be possible to, in the same view see if a beneficiary was eligible for the support but won't receive it due to not being compliant.

**Comment by lyn88** [comment]
A new button tab/button "Enrolments" is proposed to be available beside the "Beneficiaries" button to display the list of all enrolled members including the ones that are not compliant. 

![Screenshot 2024-10-29 at 12 08 16 PM](https://github.com/user-attachments/assets/e62da58c-f077-4db9-b984-12de4ae12186)

![Screenshot 2024-10-29 at 12 17 14 PM](https://github.com/user-attachments/assets/e681a86e-6d83-40ca-bc4d-e04802886a75)

**Comment by reichie020212** [comment]
as discussed in the meeting with @emjay0921 @singhkaranvir25 and @lyn88 , the following improvements is needed.

- Change the text of page the when clicking the `Beneficiaries` to `Cycle Beneficiaries`.
- Find a suitable icon and change the icon of one of the buttons: `Beneficiaries` and `Enrollments`.
- Find a suitable icon and change the icon of the buttons `Entitlements` and `Payments`

**Comment by anjclarise** [comment]
@emjay0921 I can't seem to find the DSWD modules for testing this ticket in runboat 
![Image](https://github.com/user-attachments/assets/c156f125-fee2-4dbd-b618-7cb00d5f81d1)

**Comment by anjclarise** [comment]
Verified this ticket and working as expected. 

Test steps:

1. Install or Upgrade spp_programs_compliance_criteria.
2. Open or Create new program (Make sure to add some compliance criteria).
3. Open or Create new cycle.
4. Check if Enrollments Button on top (Before Beneficiaries) exists.
5. Click on Compliance Criteria and check if the Enrollments Count is still the same.
6. Compare the List from Beneficiaries and Enrollments if it is the expected behavior.

Enrolments beside beneficiaries: 
![Image](https://github.com/user-attachments/assets/fc0e533c-cc33-4418-9e16-8f32c575ea3f)

Enrolments page when opened: 
![Image](https://github.com/user-attachments/assets/03f58cc0-7226-4f89-b3fd-6c608a5c9e8e)

Change the text of page the when clicking the Beneficiaries to Cycle Beneficiaries:
![Image](https://github.com/user-attachments/assets/c3d2e512-6e65-45e3-9472-a0ce82462c26)

Beneficiaries, enrolments and payments icons:
![Image](https://github.com/user-attachments/assets/da6ffaa5-0116-44ce-9497-ce9045ddcf25)
